create table Bank (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table CreditCard (
    balance integer,
    creditLimit integer,
    number integer,
    id bigint generated by default as identity,
    owningBank_id bigint,
    pincode_id bigint,
    primary key (id)
);

create table Customer (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table Customer_Address (
    addresses_id bigint not null,
    owners_id bigint not null,
    primary key (addresses_id, owners_id)
);
create table Customer_CreditCard (
    Customer_id bigint not null,
    ownedCards_id bigint not null,
    primary key (Customer_id, ownedCards_id)
);

create table Pincode (
    count integer,
    id bigint generated by default as identity,
    code varchar(255),
    primary key (id)
);

alter table if exists CreditCard
    add constraint FKnwxb2pvuwnkoifgrp2d14pla0
        foreign key (owningBank_id)
        references Bank;
alter table if exists CreditCard
    add constraint FKfky0y471d7n8cebc1oe28idci
        foreign key (pincode_id)
        references Pincode;

alter table if exists Customer_Address
    add constraint FK5ov3y8x18tb2tfs01klxn7g7o
       foreign key (addresses_id)
       references Address;
alter table if exists Customer_Address
    add constraint FKpunprton0xne8mjk0r6carq6n
        foreign key (owners_id)
        references Customer;
alter table if exists Customer_CreditCard
    add constraint FKpdhxqi11pvv91b8p82qhuutay
        foreign key (ownedCards_id)
        references CreditCard;
alter table if exists Customer_CreditCard
    add constraint FKbcd9tsn3uxf491h4bv3vo023m
        foreign key (Customer_id)
        references Customer;
